
#Got a new script! Snagged this bad boy from
#https://github.com/pestrada/android-tdd-playground/blob/master/.travis.yml
language: android
jdk: oraclejdk8
sudo: false

android:
 components:
   - platform-tools
   - tools
   - build-tools-30.0.3
   - android-30
   - sys-img-armeabi-v7a-android-30
   - sys-img-
   - extra-android-m2repository

before_install:
  - yes | sdkmanager --update
  
before_script:
 # Create and start emulator
 - echo no | android create avd --force -n test -t android-30 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &
script: ./gradlew connectedAndroidTest
